<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <RootNamespace>WanKePos.App</RootNamespace>
    <AssemblyName>WanKePos</AssemblyName>

  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="WPF-UI" Version="3.0.5" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.3.2" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.1" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.8" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\WanKePos.Domain\WanKePos.Domain.csproj" />
    <ProjectReference Include="..\WanKePos.Infrastructure\WanKePos.Infrastructure.csproj" />
  </ItemGroup>
</Project>
